// movies
export const SET_MOVIES_LIST = 'SET_MOVIES_LIST';
export const ADD_MOVIE_TO_FAVORITE = 'ADD_MOVIE_TO_FAVORITE';
export const ADD_FAVORITE_MOVIES = 'ADD_FAVORITE_MOVIE';
export const REMOVE_MOVIE_FROM_FAVORITE = 'REMOVE_MOVIE_FROM_FAVORITE';
export const TOGGLE_FETCHING_STATUS = 'TOGGLE_FETCHING_STATUS';
export const TOGGLE_SUBMITTING_STATUS = 'TOGGLE_SUBMITTING_STATUS';

// auth
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SAVE_USER = 'SAVE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

